package com.godsofmecraft.sosmod.datagen;

import com.godsofmecraft.sosmod.block.ModBlocks;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricTagProvider;
import net.minecraft.registry.RegistryWrapper;
import net.minecraft.registry.tag.BlockTags;

import java.util.concurrent.CompletableFuture;

    public class ModBlockTagProvider extends FabricTagProvider.BlockTagProvider {
        public ModBlockTagProvider(FabricDataOutput output, CompletableFuture<RegistryWrapper.WrapperLookup> registriesFuture) {
            super(output, registriesFuture);


        }



        @Override
        protected void configure(RegistryWrapper.WrapperLookup arg) {

            getOrCreateTagBuilder(BlockTags.PICKAXE_MINEABLE)
                    .add(ModBlocks.DRIPSTONE_STAIRS)
                    .add(ModBlocks.DRIPSTONE_SLAB)
                    .add(ModBlocks.DRIPSTONE_WALL)
                    .add(ModBlocks.PACKED_MUD_STAIRS)
                    .add(ModBlocks.PACKED_MUD_SLAB)
                    .add(ModBlocks.PACKED_MUD_WALL)
                    .add(ModBlocks.HONEYCOMB_BLOCK_STAIRS)
                    .add(ModBlocks.HONEYCOMB_BLOCK_SLAB)
                    .add(ModBlocks.HONEYCOMB_BLOCK_STAIRS)
                    .add(ModBlocks.QUARTZ_BRICKS_STAIRS)
                    .add(ModBlocks.QUARTZ_BRICKS_SLAB)
                    .add(ModBlocks.QUARTZ_BRICKS_WALL)
                    .add(ModBlocks.SMOOTH_BASALT_STAIRS)
                    .add(ModBlocks.SMOOTH_BASALT_SLAB)
                    .add(ModBlocks.SMOOTH_BASALT_WALL)
                    .add(ModBlocks.NETHERRACK_STAIRS)
                    .add(ModBlocks.NETHERRACK_SLAB)
                    .add(ModBlocks.NETHERRACK_WALL)
                    .add(ModBlocks.END_STONE_STAIRS)
                    .add(ModBlocks.END_STONE_SLAB)
                    .add(ModBlocks.END_STONE_WALL)                .add(ModBlocks.TERRACOTTA_STAIRS)
                    .add(ModBlocks.TERRACOTTA_SLAB)
                    .add(ModBlocks.TERRACOTTA_WALL)
                    .add(ModBlocks.WHITE_TERRACOTTA_STAIRS)
                    .add(ModBlocks.WHITE_TERRACOTTA_SLAB)
                    .add(ModBlocks.WHITE_TERRACOTTA_WALL)
                    .add(ModBlocks.LIGHT_GRAY_TERRACOTTA_STAIRS)
                    .add(ModBlocks.LIGHT_GRAY_TERRACOTTA_SLAB)
                    .add(ModBlocks.LIGHT_GRAY_TERRACOTTA_WALL)
                    .add(ModBlocks.GRAY_TERRACOTTA_STAIRS)
                    .add(ModBlocks.GRAY_TERRACOTTA_SLAB)
                    .add(ModBlocks.GRAY_TERRACOTTA_WALL)
                    .add(ModBlocks.BLACK_TERRACOTTA_STAIRS)
                    .add(ModBlocks.BLACK_TERRACOTTA_SLAB)
                    .add(ModBlocks.BLACK_TERRACOTTA_WALL)
                    .add(ModBlocks.BROWN_TERRACOTTA_STAIRS)
                    .add(ModBlocks.BROWN_TERRACOTTA_SLAB)
                    .add(ModBlocks.BROWN_TERRACOTTA_WALL)
                    .add(ModBlocks.RED_TERRACOTTA_STAIRS)
                    .add(ModBlocks.RED_TERRACOTTA_SLAB)
                    .add(ModBlocks.RED_TERRACOTTA_WALL)
                    .add(ModBlocks.ORANGE_TERRACOTTA_STAIRS)
                    .add(ModBlocks.ORANGE_TERRACOTTA_SLAB)
                    .add(ModBlocks.ORANGE_TERRACOTTA_WALL)
                    .add(ModBlocks.YELLOW_TERRACOTTA_STAIRS)
                    .add(ModBlocks.YELLOW_TERRACOTTA_SLAB)
                    .add(ModBlocks.YELLOW_TERRACOTTA_WALL)
                    .add(ModBlocks.LIME_TERRACOTTA_STAIRS)
                    .add(ModBlocks.LIME_TERRACOTTA_SLAB)
                    .add(ModBlocks.LIME_TERRACOTTA_WALL)
                    .add(ModBlocks.GREEN_TERRACOTTA_STAIRS)
                    .add(ModBlocks.GREEN_TERRACOTTA_SLAB)
                    .add(ModBlocks.GREEN_TERRACOTTA_WALL)
                    .add(ModBlocks.CYAN_TERRACOTTA_STAIRS)
                    .add(ModBlocks.CYAN_TERRACOTTA_SLAB)
                    .add(ModBlocks.CYAN_TERRACOTTA_WALL)
                    .add(ModBlocks.LIGHT_BLUE_TERRACOTTA_STAIRS)
                    .add(ModBlocks.LIGHT_BLUE_TERRACOTTA_SLAB)
                    .add(ModBlocks.LIGHT_BLUE_TERRACOTTA_WALL)
                    .add(ModBlocks.BLUE_TERRACOTTA_STAIRS)
                    .add(ModBlocks.BLUE_TERRACOTTA_SLAB)
                    .add(ModBlocks.BLUE_TERRACOTTA_WALL)
                    .add(ModBlocks.PURPLE_TERRACOTTA_STAIRS)
                    .add(ModBlocks.PURPLE_TERRACOTTA_SLAB)
                    .add(ModBlocks.PURPLE_TERRACOTTA_WALL)
                    .add(ModBlocks.MAGENTA_TERRACOTTA_STAIRS)
                    .add(ModBlocks.MAGENTA_TERRACOTTA_SLAB)
                    .add(ModBlocks.MAGENTA_TERRACOTTA_WALL)
                    .add(ModBlocks.PINK_TERRACOTTA_STAIRS)
                    .add(ModBlocks.PINK_TERRACOTTA_SLAB)
                    .add(ModBlocks.PINK_TERRACOTTA_WALL)
                    .add(ModBlocks.WHITE_CONCRETE_STAIRS)
                    .add(ModBlocks.WHITE_CONCRETE_SLAB)
                    .add(ModBlocks.WHITE_CONCRETE_WALL)
                    .add(ModBlocks.LIGHT_GRAY_CONCRETE_STAIRS)
                    .add(ModBlocks.LIGHT_GRAY_CONCRETE_SLAB)
                    .add(ModBlocks.LIGHT_GRAY_CONCRETE_WALL)
                    .add(ModBlocks.GRAY_CONCRETE_STAIRS)
                    .add(ModBlocks.GRAY_CONCRETE_SLAB)
                    .add(ModBlocks.GRAY_CONCRETE_WALL)
                    .add(ModBlocks.BLACK_CONCRETE_STAIRS)
                    .add(ModBlocks.BLACK_CONCRETE_SLAB)
                    .add(ModBlocks.BLACK_CONCRETE_WALL)
                    .add(ModBlocks.BROWN_CONCRETE_STAIRS)
                    .add(ModBlocks.BROWN_CONCRETE_SLAB)
                    .add(ModBlocks.BROWN_CONCRETE_WALL)
                    .add(ModBlocks.RED_CONCRETE_STAIRS)
                    .add(ModBlocks.RED_CONCRETE_SLAB)
                    .add(ModBlocks.RED_CONCRETE_WALL)
                    .add(ModBlocks.ORANGE_CONCRETE_STAIRS)
                    .add(ModBlocks.ORANGE_CONCRETE_SLAB)
                    .add(ModBlocks.ORANGE_CONCRETE_WALL)
                    .add(ModBlocks.YELLOW_CONCRETE_STAIRS)
                    .add(ModBlocks.YELLOW_CONCRETE_SLAB)
                    .add(ModBlocks.YELLOW_CONCRETE_WALL)
                    .add(ModBlocks.LIME_CONCRETE_STAIRS)
                    .add(ModBlocks.LIME_CONCRETE_SLAB)
                    .add(ModBlocks.LIME_CONCRETE_WALL)
                    .add(ModBlocks.GREEN_CONCRETE_STAIRS)
                    .add(ModBlocks.GREEN_CONCRETE_SLAB)
                    .add(ModBlocks.GREEN_CONCRETE_WALL)
                    .add(ModBlocks.CYAN_CONCRETE_STAIRS)
                    .add(ModBlocks.CYAN_CONCRETE_SLAB)
                    .add(ModBlocks.CYAN_CONCRETE_WALL)
                    .add(ModBlocks.LIGHT_BLUE_CONCRETE_STAIRS)
                    .add(ModBlocks.LIGHT_BLUE_CONCRETE_SLAB)
                    .add(ModBlocks.LIGHT_BLUE_CONCRETE_WALL)
                    .add(ModBlocks.BLUE_CONCRETE_STAIRS)
                    .add(ModBlocks.BLUE_CONCRETE_SLAB)
                    .add(ModBlocks.BLUE_CONCRETE_WALL)
                    .add(ModBlocks.PURPLE_CONCRETE_STAIRS)
                    .add(ModBlocks.PURPLE_CONCRETE_SLAB)
                    .add(ModBlocks.PURPLE_CONCRETE_WALL)
                    .add(ModBlocks.MAGENTA_CONCRETE_STAIRS)
                    .add(ModBlocks.MAGENTA_CONCRETE_SLAB)
                    .add(ModBlocks.MAGENTA_CONCRETE_WALL)
                    .add(ModBlocks.PINK_CONCRETE_STAIRS)
                    .add(ModBlocks.PINK_CONCRETE_SLAB)
                    .add(ModBlocks.PINK_CONCRETE_WALL);

            getOrCreateTagBuilder(BlockTags.SHOVEL_MINEABLE)
                    .add(ModBlocks.CLAY_STAIRS)
                    .add(ModBlocks.CLAY_SLAB)
                    .add(ModBlocks.CLAY_WALL);

            getOrCreateTagBuilder(BlockTags.WALLS)
                    .add(ModBlocks.DRIPSTONE_WALL)
                    .add(ModBlocks.PACKED_MUD_WALL)
                    .add(ModBlocks.HONEYCOMB_BLOCK_WALL)
                    .add(ModBlocks.CLAY_WALL)
                    .add(ModBlocks.QUARTZ_BRICKS_WALL)
                    .add(ModBlocks.SMOOTH_BASALT_WALL)
                    .add(ModBlocks.NETHERRACK_WALL)
                    .add(ModBlocks.END_STONE_WALL)
                    .add(ModBlocks.TERRACOTTA_WALL)
                    .add(ModBlocks.WHITE_TERRACOTTA_WALL)
                    .add(ModBlocks.LIGHT_GRAY_TERRACOTTA_WALL)
                    .add(ModBlocks.GRAY_TERRACOTTA_WALL)
                    .add(ModBlocks.BLACK_TERRACOTTA_WALL)
                    .add(ModBlocks.BROWN_TERRACOTTA_WALL)
                    .add(ModBlocks.RED_TERRACOTTA_WALL)
                    .add(ModBlocks.ORANGE_TERRACOTTA_WALL)
                    .add(ModBlocks.YELLOW_TERRACOTTA_WALL)
                    .add(ModBlocks.LIME_TERRACOTTA_WALL)
                    .add(ModBlocks.GREEN_TERRACOTTA_WALL)
                    .add(ModBlocks.CYAN_TERRACOTTA_WALL)
                    .add(ModBlocks.LIGHT_BLUE_TERRACOTTA_WALL)
                    .add(ModBlocks.BLUE_TERRACOTTA_WALL)
                    .add(ModBlocks.PURPLE_TERRACOTTA_WALL)
                    .add(ModBlocks.MAGENTA_TERRACOTTA_WALL)
                    .add(ModBlocks.PINK_TERRACOTTA_WALL)
                    .add(ModBlocks.WHITE_CONCRETE_WALL)
                    .add(ModBlocks.LIGHT_GRAY_CONCRETE_WALL)
                    .add(ModBlocks.GRAY_CONCRETE_WALL)
                    .add(ModBlocks.BLACK_CONCRETE_WALL)
                    .add(ModBlocks.BROWN_CONCRETE_WALL)
                    .add(ModBlocks.RED_CONCRETE_WALL)
                    .add(ModBlocks.ORANGE_CONCRETE_WALL)
                    .add(ModBlocks.YELLOW_CONCRETE_WALL)
                    .add(ModBlocks.LIME_CONCRETE_WALL)
                    .add(ModBlocks.GREEN_CONCRETE_WALL)
                    .add(ModBlocks.CYAN_CONCRETE_WALL)
                    .add(ModBlocks.LIGHT_BLUE_CONCRETE_WALL)
                    .add(ModBlocks.BLUE_CONCRETE_WALL)
                    .add(ModBlocks.PURPLE_CONCRETE_WALL)
                    .add(ModBlocks.MAGENTA_CONCRETE_WALL)
                    .add(ModBlocks.PINK_CONCRETE_WALL)
                    .add(ModBlocks.HONEYCOMB_BLOCK_WALL);

            getOrCreateTagBuilder(BlockTags.FLOWERS)
                    .add(ModBlocks.MAGENTA_TULIP)
                    .add(ModBlocks.YELLOW_TULIP)
                    .add(ModBlocks.PURPLE_TULIP)
                    .add(ModBlocks.RAINBOW_TULIP)
                    .add(ModBlocks.RED_WHITE_TULIP)
                    .add(ModBlocks.ORANGE_YELLOW_TULIP)
                    .add(ModBlocks.PURPLE_YELLOW_TULIP)
                    .add(ModBlocks.PINK_LILY_OF_THE_VALLEY)
                    .add(ModBlocks.YELLOW_ORCHID)
                    .add(ModBlocks.ORANGE_ORCHID)
                    .add(ModBlocks.GREEN_ORCHID)
                    .add(ModBlocks.PINK_ORCHID)
                    .add(ModBlocks.PURPLE_ORCHID)
                    .add(ModBlocks.RED_ORCHID)
                    .add(ModBlocks.WHITE_ORCHID)
                    .add(ModBlocks.MAGENTA_WHITE_ORCHID)
                    .add(ModBlocks.PINK_YELLOW_ORCHID);
              


            getOrCreateTagBuilder(BlockTags.SMALL_FLOWERS)
                    .add(ModBlocks.MAGENTA_TULIP)
                    .add(ModBlocks.YELLOW_TULIP)
                    .add(ModBlocks.PURPLE_TULIP)
                    .add(ModBlocks.RAINBOW_TULIP)
                    .add(ModBlocks.RED_WHITE_TULIP)
                    .add(ModBlocks.ORANGE_YELLOW_TULIP)
                    .add(ModBlocks.PURPLE_YELLOW_TULIP)
                    .add(ModBlocks.PINK_LILY_OF_THE_VALLEY)
                    .add(ModBlocks.YELLOW_ORCHID)
                    .add(ModBlocks.ORANGE_ORCHID)
                    .add(ModBlocks.GREEN_ORCHID)
                    .add(ModBlocks.PINK_ORCHID)
                    .add(ModBlocks.PURPLE_ORCHID)
                    .add(ModBlocks.RED_ORCHID)
                    .add(ModBlocks.WHITE_ORCHID)
                    .add(ModBlocks.MAGENTA_WHITE_ORCHID)
                    .add(ModBlocks.PINK_YELLOW_ORCHID);





        }
    }
